ShoesFactory/ShoesFactory.WEB/Models/MaterialViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ShoesFactory.WEB.Models
{
    public class MaterialViewModel
    {
        public MaterialViewModel()
        {
        }

        public MaterialViewModel(string name, string summary)
        {
            Name = name;
            Summary = summary;
        }

        public MaterialViewModel(int id, string name, string summary)
        {
            Id = id;
            Name = name;
            Summary = summary;
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Summary { get; set; }
        public int Count { get; set; }
    }
}

ShoesFactory/ShoesFactory.WEB/Models/SuplierViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ShoesFactory.WEB.Models
{
    public class SupplierDTO
    {
        public SupplierDTO()
        {
        }

        public SupplierDTO(string name)
        {
            Name = name;
        }

        public SupplierDTO(int id, string name)
        {
            Id = id;
            Name = name;
        }

        public int Id { get; set; }
        public string Name { get; set; }
    }
}

ShoesFactory/ShoesFactory.WEB/Models/SupplierViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ShoesFactory.WEB.Models
{
    public class SupplierViewModel
    {
        public SupplierViewModel()
        {
        }

        public SupplierViewModel(string name)
        {
            Name = name;
        }

        public SupplierViewModel(int id, string name)
        {
            Id = id;
            Name = name;
        }

        public int Id { get; set; }
        public string Name { get; set; }
    }
}

ShoesFactory/ShoesFactory.WEB/Models/SupplyViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ShoesFactory.WEB.Models
{
    public class SupplyViewModel
    {
        public SupplyViewModel()
        {
        }
       
        public SupplyViewModel(string materialName, string supplierName, int count, double price)
        {
            MaterialName = materialName;
            SupplierName = supplierName;
            Count = count;
            Price = price;
        }
        public int Id { get; set; }
        public  string SupplierName { get; set; }
        public string MaterialName { get; set; }
        public int MaterialId { get; set; }
        public int SupplierId { get; set; }
        public int Count { get; set; }
        public double Price { get; set; }       
    }
}

ShoesFactory/ShoesFactory.WEB/Controllers/HomeController.cs
using System.Web.Mvc;

namespace ShoesFactory.WEB.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {        
            return View();
        }
    }
}

ShoesFactory/ShoesFactory.WEB/Controllers/ShoesFactoryController.cs
using AutoMapper;
using ShoesFactory.BLL.DTO;
using ShoesFactory.BLL.Interfaces;
using ShoesFactory.WEB.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShoesFactory.WEB.Controllers
{
    public class ShoesFactoryController : Controller
    {
        ISupplyService supplyService;       
        public ShoesFactoryController(ISupplyService splServ)
        {
            supplyService = splServ;
        }
        public ActionResult Supplies()
        {
            IEnumerable<SupplyDTO> supplyDtos = supplyService.GetAllSupplies();
            var mapper = new MapperConfiguration(cfg => cfg.CreateMap<SupplyDTO, SupplyViewModel>()).CreateMapper();
            var supplies = mapper.Map<IEnumerable<SupplyDTO>, List<SupplyViewModel>>(supplyDtos);
            return View(supplies);
        }
        public ActionResult AddSupply(SupplyViewModel model)
        {
            supplyService.AddSupply(new MaterialDTO(model.MaterialName, ""), model.SupplierName, model.Count, model.Price);
            return RedirectToAction("Supplies", supplyService.GetAllSupplies());
        }
        [HttpGet]
        public JsonResult GetSupply(int id)
        {
            var mapper = new MapperConfiguration(cfg => cfg.CreateMap<SupplyDTO, SupplyViewModel>()).CreateMapper();
            var supply = mapper.Map<SupplyDTO, SupplyViewModel>(supplyService.GetSupply(id));
            var jsondata = supply;
            return Json(jsondata, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult DeleteSupply(int id)
        {
            supplyService.DeleteSupply(id);
            return RedirectToAction("Supplies");
        }
        public ActionResult Materials()
        {
            IEnumerable<MaterialDTO> materialDtos = supplyService.GetAllMaterials();
            var mapper = new MapperConfiguration(cfg => cfg.CreateMap<MaterialDTO, MaterialViewModel>()).CreateMapper();
            var materials = mapper.Map<IEnumerable<MaterialDTO>, List<MaterialViewModel>>(materialDtos);
            return View(materials);
        }
        public ActionResult AddMaterial(MaterialViewModel material)
        {
            var mapper = new MapperConfiguration(cfg => cfg.CreateMap<MaterialViewModel, MaterialDTO>()).CreateMapper();
            var newMaterial = mapper.Map<MaterialViewModel, MaterialDTO>(material);
            supplyService.AddMaterial(newMaterial);
            return RedirectToAction("Materials");
        }
        [HttpGet]
        public ActionResult DeleteMaterial(int id)
        {
           supplyService.DeleteMaterial(id);
            var x = supplyService.GetAllSupplies();
           return RedirectToAction("Materials");
        }

        [HttpGet]
        public JsonResult GetMaterial(int id)
        {
            var mapper = new MapperConfiguration(cfg => cfg.CreateMap<MaterialDTO, MaterialViewModel>()).CreateMapper();
            var material = mapper.Map<MaterialDTO, MaterialViewModel>(supplyService.GetMaterial(id));
            var jsondata = material;
            return Json(jsondata, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Suppliers()
        {
            IEnumerable<SupplierDTO> supplierDtos = supplyService.GetAllSuppliers();
            var mapper = new MapperConfiguration(cfg => cfg.CreateMap<SupplierDTO, SupplierViewModel>()).CreateMapper();
            var suppliers = mapper.Map<IEnumerable<SupplierDTO>, List<SupplierViewModel>>(supplierDtos);
            return View(suppliers);
        }
        public ActionResult AddSupplier(SupplierViewModel supplier)
        {
            var mapper = new MapperConfiguration(cfg => cfg.CreateMap<SupplierViewModel, SupplierDTO>()).CreateMapper();
            var newSupplier = mapper.Map<SupplierViewModel, SupplierDTO>(supplier);
            supplyService.AddSupplier(newSupplier);
            return RedirectToAction("Suppliers");
        }
        [HttpGet]
        public ActionResult DeleteSupplier(int id)
        {
            supplyService.DeleteSupplier(id);
            var x = supplyService.GetAllSuppliers();
            return RedirectToAction("Suppliers");
        }

        [HttpGet]
        public JsonResult GetSupplier(int id)
        {
            var mapper = new MapperConfiguration(cfg => cfg.CreateMap<SupplierDTO, SupplierViewModel>()).CreateMapper();
            var supplier = mapper.Map<SupplierDTO, SupplierViewModel>(supplyService.GetSupplier(id));
            var jsondata = supplier;
            return Json(jsondata, JsonRequestBehavior.AllowGet);
        }
    }
}

ShoesFactory/ShoesFactory.WEB/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Begin";
}

<div class="row text-center align-items-center">
    <br />
    <br />
    <button type="button" class="btn btn-primary btn-lg" onclick="location.href='@Url.Action("Materials", "ShoesFactory")'">Почати роботу</button>
</div>

ShoesFactory/ShoesFactory.WEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - ShoesFactory</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    
    <div class="container body-content">
        @if (ViewBag.Title != "Begin")
        {
            switch (ViewBag.Title)
            {
                case "Supplies":
                    <div class="row">
                        <div class="col-md-12">
                            <ul class="nav nav-tabs">
                                <li class="nav-item">
                                    <a class="nav-link" href="/ShoesFactory/Materials">Матеріали</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link active" href="/ShoesFactory/Supplies">Поставки</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link " href="/ShoesFactory/Suppliers">Поставники</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="/ShoesFactory/Shoes">Моделі взуття</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="/ShoesFactory/Consigment">Партії</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="/ShoesFactory/Employers">Працівники</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    break;

                case "Materials":
                    <div class="row">
                        <div class="col-md-12">
                            <ul class="nav nav-tabs">
                                <li class="nav-item">
                                    <a class="nav-link active" href="/ShoesFactory/Materials">Матеріали</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link " href="/ShoesFactory/Supplies">Поставки</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="/ShoesFactory/Suppliers">Поставники</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="/ShoesFactory/Shoes">Моделі взуття</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="/ShoesFactory/Consigment">Партії</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="/ShoesFactory/Employers">Працівники</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    break;

                case "Suppliers":
                    <div class="row">
                        <div class="col-md-12">
                            <ul class="nav nav-tabs">
                                <li class="nav-item">
                                    <a class="nav-link" href="/ShoesFactory/Materials">Матеріали</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link " href="/ShoesFactory/Supplies">Поставки</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link active" href="/ShoesFactory/Suppliers">Поставники</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="/ShoesFactory/Shoes">Моделі взуття</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="/ShoesFactory/Consigment">Партії</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="/ShoesFactory/Employers">Працівники</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    break;
            }

        }

        @RenderBody()
        <footer>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script src="~/Scripts/MyScript.js"></script>
</body>
</html>

ShoesFactory/ShoesFactory.WEB/Views/ShoesFactory/Materials.cshtml
@model IEnumerable<ShoesFactory.WEB.Models.MaterialViewModel>
@using ShoesFactory.WEB.Models;
@using ShoesFactory.BLL.Services;
@{
    ViewBag.Title = "Materials";
}

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Редагування</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="/ShoesFactory/AddMaterial" method="post" id="editForm">
                    <input type="hidden" name="Id" value="" />
                    <div class="form-group row">
                        <label for="MaterialName" class="col-sm-2 col-form-label">Назва</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="MaterialName" name="Name" value="" placeholder="">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="Summary" class="col-sm-2 col-form-label">Опис</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="Summary" name="Summary" value="" placeholder="">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="Count" class="col-sm-2 col-form-label">Кількість</label>
                        <div class="col-sm-10">
                            <input type="number" class="form-control" id="Count" name="Count" value="" placeholder="">
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button form="editForm" class="btn btn-primary" type="submit">Добре</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Відмінити</button>
            </div>
        </div>
    </div>
</div>


<div class="modal fade" id="exampleModal1" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel1" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel1">Видалити запис?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="/ShoesFactory/DeleteMaterial" method="get" id="deleteMaterial">
                    <input type="hidden" name="id" value="" id="deleteId" />
                </form>
            </div>
            <div class="modal-footer">
                <button form="deleteMaterial" class="btn btn-primary" type="submit" id="DeleteAprove">Так</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Ні</button>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <table class="table table-hover border-bottom">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Назва</th>
                    <th scope="col">Опис</th>
                    <th scope="col">Кількість</th>
                    <th scope="col"></th>
                </tr>
            </thead>

            <tbody class="">
                @foreach (var item in Model)
                {
                    <tr>
                        <th scope="row">@item.Id</th>
                        <td class="id">@item.Name</td>
                        <td>@item.Summary</td>
                        <td>@item.Count</td>
                        <td class="text-right pr-0">
                            <a class="btn btn-success mr-2 updateMaterial" href="#" role="button" data-toggle="modal" data-target="#exampleModal" id="">Редагувати</a>
                            <a class="btn btn-danger deleteButton" href="#" role="button" data-toggle="modal" data-target="#exampleModal1">Видалити</a>
                        </td>
                    </tr>
                }

            </tbody>
        </table>
        <div class="text-right">
            <a class="btn btn-primary px-3" href="#" role="button" data-toggle="modal" data-target="#exampleModal" id="addButton">Додати</a>
        </div>
    </div>
</div>

ShoesFactory/ShoesFactory.WEB/Views/ShoesFactory/Suppliers.cshtml
@model IEnumerable<ShoesFactory.WEB.Models.SupplierViewModel>
@using ShoesFactory.WEB.Models;
@using ShoesFactory.BLL.Services;
@{
    ViewBag.Title = "Suppliers";
}

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Редагування</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="/ShoesFactory/AddSupplier" method="post" id="editForm">
                    <input type="hidden" name="Id" value="" />
                    <div class="form-group row">
                        <label for="MaterialName" class="col-sm-2 col-form-label">Ім'я</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="MaterialName" name="Name" value="" placeholder="">
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button form="editForm" class="btn btn-primary" type="submit">Добре</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Відмінити</button>
            </div>
        </div>
    </div>
</div>


<div class="modal fade" id="exampleModal1" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel1" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel1">Видалити запис?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="/ShoesFactory/DeleteSupplier" method="get" id="deleteMaterial">
                    <input type="hidden" name="id" value="" id="deleteId" />
                </form>
            </div>
            <div class="modal-footer">
                <button form="deleteMaterial" class="btn btn-primary" type="submit" id="DeleteAprove">Так</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Ні</button>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <table class="table table-hover border-bottom">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Ім'я</th>
                    <th scope="col"></th>
                </tr>
            </thead>

            <tbody class="">
                @foreach (var item in Model)
                {
                    <tr>
                        <th scope="row">@item.Id</th>
                        <td class="id">@item.Name</td>
                        <td class="text-right pr-0">
                            <a class="btn btn-success mr-2 updateSupplier" href="#" role="button" data-toggle="modal" data-target="#exampleModal" id="">Редагувати</a>
                            <a class="btn btn-danger deleteButton" href="#" role="button" data-toggle="modal" data-target="#exampleModal1">Видалити</a>
                        </td>
                    </tr>
                }

            </tbody>
        </table>
        <div class="text-right">
            <a class="btn btn-primary px-3" href="#" role="button" data-toggle="modal" data-target="#exampleModal" id="addButton">Додати</a>
        </div>
    </div>
</div>

ShoesFactory/ShoesFactory.WEB/Views/ShoesFactory/Supplies.cshtml
@model IEnumerable<ShoesFactory.WEB.Models.SupplyViewModel>
@using ShoesFactory.WEB.Models;
@using ShoesFactory.BLL.Services;
@{
    ViewBag.Title = "Supplies";
}

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Редагування</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="/ShoesFactory/AddSupply" method="post" id="AddSupply">
                    <input type="hidden" name="Id" value="" />
                    <div class="form-group row">
                        <label for="MaterialName" class="col-sm-2 col-form-label">Назва матеріалу</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="MaterialName" name="MaterialName" value="" placeholder="">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="SupplierName" class="col-sm-2 col-form-label">Ім'я поставника</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="SupplierName" name="SupplierName" value="" placeholder="">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="Count" class="col-sm-2 col-form-label">Кількість</label>
                        <div class="col-sm-10">
                            <input type="number" class="form-control" id="Count" name="Count" value="" placeholder="">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="Price" class="col-sm-2 col-form-label">Ціна</label>
                        <div class="col-sm-10">
                            <input type="number" class="form-control" id="Price" name="Price" value="" placeholder="">
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button form="AddSupply" class="btn btn-primary" type="submit">Добре</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Відмінити</button>
            </div>
        </div>
    </div>
</div>


<div class="modal fade" id="exampleModal1" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel1" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel1">Видалити запис?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="/ShoesFactory/DeleteSupply" method="get" id="deleteMaterial">
                    <input type="hidden" name="id" value="" id="deleteId" />
                </form>
            </div>
            <div class="modal-footer">
                <button form="deleteMaterial" class="btn btn-primary" type="submit" id="DeleteAprove">Так</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Ні</button>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <table class="table table-hover border-bottom">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Матеріал</th>
                    <th scope="col">Поставник</th>
                    <th scope="col">Ціна</th>
                    <th scope="col">Кількість</th>
                    <th scope="col"></th>
                </tr>
            </thead>

            <tbody class="">
                @foreach (var item in Model)
                {
                    <tr>
                        <th scope="row">@item.Id</th>
                        <td class="id">@item.MaterialId</td>
                        <td>@item.SupplierId</td>
                        <td>@item.Price</td>
                        <td>@item.Count</td>
                        <td class="text-right pr-0">
                            <a class="btn btn-success mr-2 updateSupply" href="#" role="button" data-toggle="modal" data-target="#exampleModal" id="">Редагувати</a>
                            <a class="btn btn-danger deleteButton" href="#" role="button" data-toggle="modal" data-target="#exampleModal1">Видалити</a>
                        </td>
                    </tr>
                }

            </tbody>
        </table>
        <div class="text-right">
            <a class="btn btn-primary px-3" href="#" role="button" data-toggle="modal" data-target="#exampleModal">Додати</a>
        </div>
    </div>
</div>